[package]
authors = ["Kisio Digital <team.coretools@kisio.org>", "Guillaume Pinot <texitoi@texitoi.eu>"]
name = "transit_model"
version = "0.11.1"
license = "AGPL-3.0-only"
description = "Transit data management"
repository = "https://github.com/CanalTP/transit_model"
keywords = ["ntfs", "gtfs", "netex", "navitia", "transit"]
edition = "2018"

[badges]
travis-ci = { repository = "CanalTP/transit_model" }

[workspace]
members = [
  "collection",
  "relations",
  "model-builder",
  "transit_model_procmacro",
]

[features]
stop_location = []

[dependencies]
chrono = "0.4"
csv = "1.0"
derivative = "1"
failure = "0.1"
geo = "0.12"
geo-types = "0.4"
iso4217 = "0.3"
lazy_static = "1.2"
log = "0.4"
minidom = "0.11"
num-traits = "0.2"
pretty_assertions = "0.6"
proj = { version = "0.10", optional = true }
rust_decimal = "1.0"
serde = { version = "1", features = ["derive"] }
serde_json = "1"
tempfile = "3"
time-parse = "0.1"
walkdir = "2.1"
wkt = "0.5"
zip = "0.5"
transit_model_collection = { version = "0.1", path = "./collection" }
transit_model_procmacro = { version = "0.1", path = "./transit_model_procmacro" }
transit_model_relations = { version = "0.1", path = "./relations" }

[[test]]
name = "kv12ntfs"
path = "tests/read_kv1.rs"
required-features = ["proj"]

[[bench]]
name = "read_kv1"
path = "benches/read_kv1.rs"
required-features = ["proj"]

[[test]]
name = "transxchange2ntfs"
path = "tests/read_transxchange.rs"
required-features = ["proj"]

[[bench]]
name = "read_transxchange"
path = "benches/read_transxchange.rs"
required-features = ["transxchange"]

[[test]]
name = "netexidf2ntfs"
path = "tests/netexidf2ntfs.rs"
required-features = ["proj"]

[dev-dependencies]
approx = "0.3"
rust_decimal_macros = "1.0"
