[package]
name = "transit_model_builder"
version = "0.2.0"
authors = ["Antoine Desbordes <antoine.desbordes@gmail.com>"]
edition = "2018"
license = "AGPL-3.0"
description = "A crate to easily build a transit_model::Model"

[dependencies]
transit_model = { path = "../transit_model", version = "0.5" }
