name: Publish on crates.io
on:
  release:
    types: [published]

env:
  SLACK_TEXT: '{"attachments":[{
                "text":"Un job demande votre attention !","color":"#D00000",
                "fields":[{"title": ":warning: Action URL","value": "https://github.com/CanalTP/transit_model/actions/runs/actions/runs/${{ env.GITHUB_RUN_ID}}"
                }]}]}'

jobs:
  publish:
    name: Publish
    runs-on: ubuntu-latest
    container: kisiodigital/rust-ci:latest-proj7.2.1
    steps:
    - uses: actions/checkout@master
    - name: Cargo login
      uses: actions-rs/cargo@v1
      with:
        command: login
        args: -- ${{ secrets.CARGO_TOKEN }}
    - name: Publish transit_model
      uses: actions-rs/cargo@v1
      with:
        command: publish
        args: --all-features
    - name: slack notification (the job has failed)
      if: failure() && github.ref == 'ref/head/master'
      run: |
        curl -s -X POST -H "Content-Type: application/json" -d '${{ env.SLACK_TEXT }}' ${{ secrets.SLACK_CORE_TOOLS_TEAM_URL }}
